package surcharge.ui.theme
import androidx.compose.ui.graphics.Color

val earth_theme_light_primary = Color(0xFF954A00)
val earth_theme_light_onPrimary = Color(0xFFFFFFFF)
val earth_theme_light_primaryContainer = Color(0xFFFFDCC6)
val earth_theme_light_onPrimaryContainer = Color(0xFF301400)
val earth_theme_light_secondary = Color(0xFF755845)
val earth_theme_light_onSecondary = Color(0xFFFFFFFF)
val earth_theme_light_secondaryContainer = Color(0xFFFFDCC6)
val earth_theme_light_onSecondaryContainer = Color(0xFF2B1708)
val earth_theme_light_tertiary = Color(0xFF5F6135)
val earth_theme_light_onTertiary = Color(0xFFFFFFFF)
val earth_theme_light_tertiaryContainer = Color(0xFFE5E6AE)
val earth_theme_light_onTertiaryContainer = Color(0xFF1C1D00)
val earth_theme_light_error = Color(0xFFBA1A1A)
val earth_theme_light_errorContainer = Color(0xFFFFDAD6)
val earth_theme_light_onError = Color(0xFFFFFFFF)
val earth_theme_light_onErrorContainer = Color(0xFF410002)
val earth_theme_light_background = Color(0xFFFFFBFF)
val earth_theme_light_onBackground = Color(0xFF201A17)
val earth_theme_light_surface = Color(0xFFFFFBFF)
val earth_theme_light_onSurface = Color(0xFF201A17)
val earth_theme_light_surfaceVariant = Color(0xFFF3DED3)
val earth_theme_light_onSurfaceVariant = Color(0xFF52443B)
val earth_theme_light_outline = Color(0xFF84746A)
val earth_theme_light_inverseOnSurface = Color(0xFFFBEEE8)
val earth_theme_light_inverseSurface = Color(0xFF362F2B)
val earth_theme_light_inversePrimary = Color(0xFFFFB785)
val earth_theme_light_shadow = Color(0xFF000000)
val earth_theme_light_surfaceTint = Color(0xFF954A00)
val earth_theme_light_outlineVariant = Color(0xFFD7C3B7)
val earth_theme_light_scrim = Color(0xFF000000)

val earth_theme_dark_primary = Color(0xFFFFB785)
val earth_theme_dark_onPrimary = Color(0xFF502500)
val earth_theme_dark_primaryContainer = Color(0xFF713700)
val earth_theme_dark_onPrimaryContainer = Color(0xFFFFDCC6)
val earth_theme_dark_secondary = Color(0xFFE4BFA8)
val earth_theme_dark_onSecondary = Color(0xFF422B1B)
val earth_theme_dark_secondaryContainer = Color(0xFF5B412F)
val earth_theme_dark_onSecondaryContainer = Color(0xFFFFDCC6)
val earth_theme_dark_tertiary = Color(0xFFC8CA94)
val earth_theme_dark_onTertiary = Color(0xFF31320B)
val earth_theme_dark_tertiaryContainer = Color(0xFF47491F)
val earth_theme_dark_onTertiaryContainer = Color(0xFFE5E6AE)
val earth_theme_dark_error = Color(0xFFFFB4AB)
val earth_theme_dark_errorContainer = Color(0xFF93000A)
val earth_theme_dark_onError = Color(0xFF690005)
val earth_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val earth_theme_dark_background = Color(0xFF201A17)
val earth_theme_dark_onBackground = Color(0xFFECE0DA)
val earth_theme_dark_surface = Color(0xFF201A17)
val earth_theme_dark_onSurface = Color(0xFFECE0DA)
val earth_theme_dark_surfaceVariant = Color(0xFF52443B)
val earth_theme_dark_onSurfaceVariant = Color(0xFFD7C3B7)
val earth_theme_dark_outline = Color(0xFF9F8D83)
val earth_theme_dark_inverseOnSurface = Color(0xFF201A17)
val earth_theme_dark_inverseSurface = Color(0xFFECE0DA)
val earth_theme_dark_inversePrimary = Color(0xFF954A00)
val earth_theme_dark_shadow = Color(0xFF000000)
val earth_theme_dark_surfaceTint = Color(0xFFFFB785)
val earth_theme_dark_outlineVariant = Color(0xFF52443B)
val earth_theme_dark_scrim = Color(0xFF000000)


val earth_seed = Color(0xFFFF8921)
