package surcharge.ui.theme
import androidx.compose.ui.graphics.Color

val ocean_theme_light_primary = Color(0xFF006874)
val ocean_theme_light_onPrimary = Color(0xFFFFFFFF)
val ocean_theme_light_primaryContainer = Color(0xFF99F0FF)
val ocean_theme_light_onPrimaryContainer = Color(0xFF001F24)
val ocean_theme_light_secondary = Color(0xFF4A6267)
val ocean_theme_light_onSecondary = Color(0xFFFFFFFF)
val ocean_theme_light_secondaryContainer = Color(0xFFCDE7EC)
val ocean_theme_light_onSecondaryContainer = Color(0xFF051F23)
val ocean_theme_light_tertiary = Color(0xFF535E7D)
val ocean_theme_light_onTertiary = Color(0xFFFFFFFF)
val ocean_theme_light_tertiaryContainer = Color(0xFFDAE2FF)
val ocean_theme_light_onTertiaryContainer = Color(0xFF0E1A37)
val ocean_theme_light_error = Color(0xFFBA1A1A)
val ocean_theme_light_errorContainer = Color(0xFFFFDAD6)
val ocean_theme_light_onError = Color(0xFFFFFFFF)
val ocean_theme_light_onErrorContainer = Color(0xFF410002)
val ocean_theme_light_background = Color(0xFFFAFCFF)
val ocean_theme_light_onBackground = Color(0xFF001F2A)
val ocean_theme_light_surface = Color(0xFFFAFCFF)
val ocean_theme_light_onSurface = Color(0xFF001F2A)
val ocean_theme_light_surfaceVariant = Color(0xFFDBE4E6)
val ocean_theme_light_onSurfaceVariant = Color(0xFF3F484A)
val ocean_theme_light_outline = Color(0xFF6F797B)
val ocean_theme_light_inverseOnSurface = Color(0xFFE1F4FF)
val ocean_theme_light_inverseSurface = Color(0xFF003547)
val ocean_theme_light_inversePrimary = Color(0xFF4FD8EC)
val ocean_theme_light_shadow = Color(0xFF000000)
val ocean_theme_light_surfaceTint = Color(0xFF006874)
val ocean_theme_light_outlineVariant = Color(0xFFBFC8CA)
val ocean_theme_light_scrim = Color(0xFF000000)

val ocean_theme_dark_primary = Color(0xFF4FD8EC)
val ocean_theme_dark_onPrimary = Color(0xFF00363D)
val ocean_theme_dark_primaryContainer = Color(0xFF004F58)
val ocean_theme_dark_onPrimaryContainer = Color(0xFF99F0FF)
val ocean_theme_dark_secondary = Color(0xFFB1CBD0)
val ocean_theme_dark_onSecondary = Color(0xFF1C3438)
val ocean_theme_dark_secondaryContainer = Color(0xFF334B4F)
val ocean_theme_dark_onSecondaryContainer = Color(0xFFCDE7EC)
val ocean_theme_dark_tertiary = Color(0xFFBBC6EA)
val ocean_theme_dark_onTertiary = Color(0xFF24304D)
val ocean_theme_dark_tertiaryContainer = Color(0xFF3B4665)
val ocean_theme_dark_onTertiaryContainer = Color(0xFFDAE2FF)
val ocean_theme_dark_error = Color(0xFFFFB4AB)
val ocean_theme_dark_errorContainer = Color(0xFF93000A)
val ocean_theme_dark_onError = Color(0xFF690005)
val ocean_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val ocean_theme_dark_background = Color(0xFF001F2A)
val ocean_theme_dark_onBackground = Color(0xFFBFE9FF)
val ocean_theme_dark_surface = Color(0xFF001F2A)
val ocean_theme_dark_onSurface = Color(0xFFBFE9FF)
val ocean_theme_dark_surfaceVariant = Color(0xFF3F484A)
val ocean_theme_dark_onSurfaceVariant = Color(0xFFBFC8CA)
val ocean_theme_dark_outline = Color(0xFF899294)
val ocean_theme_dark_inverseOnSurface = Color(0xFF001F2A)
val ocean_theme_dark_inverseSurface = Color(0xFFBFE9FF)
val ocean_theme_dark_inversePrimary = Color(0xFF006874)
val ocean_theme_dark_shadow = Color(0xFF000000)
val ocean_theme_dark_surfaceTint = Color(0xFF4FD8EC)
val ocean_theme_dark_outlineVariant = Color(0xFF3F484A)
val ocean_theme_dark_scrim = Color(0xFF000000)


val ocean_seed = Color(0xFF007380)
